### ISSUE TITLE
[BUG] V3 Not Backwards Compatible with V2 JSON Specification File Code

### ISSUE THREAD

**Issue by camposeddie** [oas-tools/oas-tools#357] opened 2023-01-05 18:23 UTC
## **Describe the bug**
V3 migration documentation https://oas-tools.github.io/docs/migration says v3 is backwards compatible with v2, but that doesn't seem to be the case. The initialize function has been changed so that you can no longer pass in the oasDoc directly. I assume this was in favor of the passing the path directly instead; however, passing a config object with key `oasFile` also isn't working. In both instance, you will receive the following error where oas-tools instead looks for the default yaml path:
```
2023-01-05 18:01:76 [oas-tools] ERROR: ValidationError: Specification file at /var/nodejs/api/oas-file.yaml not found
    at validateOASFile (/var/nodejs/node_modules/@oas-tools/commons/dist/utils/modules/validator.js:13:15)
    at file:///var/nodejs/node_modules/@oas-tools/core/src/index.js:37:7
    at async Module.initialize (file:///var/nodejs/node_modules/@oas-tools/core/src/index.js:31:5)
```

## **To Reproduce**
1. Attempt to initialize oas-tools with a JSON specification file using the code described in previous v2.2.2 README notes: 
```
oasTools.initialize(oasDoc, app, function() {
  http.createServer(app).listen(8080, function() {
    console.log("App up and running!");
  });
});
```
2. Attempt to initialize oas-tools with  a JSON specification file using the code described in current documentation: 
```
oasTools.initialize(app, { oasFile: "api/openapi.json" }).then(() => {
    http.createServer(app).listen(serverPort, () => console.log("Server started!"));
})
```

## **Expected behavior**
oas-tools will initialize using JSON specification file

## **Additional context**
Code update references which demonstrate incompatibility between v3 and v2:
https://github.com/oas-tools/oas-tools/blob/v3.0.0/src/index.js#L29
https://github.com/oas-tools/oas-tools/blob/2.2.2/src/index.js#L496

**Comment by alesancor1** [comment] 2023-03-06 21:08
Hello @camposeddie, this was caused by the last version of [@oas-tools/core](https://www.npmjs.com/package/@oas-tools/core) not matching the one published at [npm registry](https://www.npmjs.com/package/oas-tools). I just fixed a problem related to this and parameter parsing, so it should be working now. You can try it by installing oas-tools develop bransh as a dependency (clone it and run `npm install ../oas-tools`, you may need to change the require from `oas-tools` to `@oas-tools/core`).

I will publish the new version to the old registry package so no changes are needed. Once it is published, I will close this issue.

**Closed** 2023-03-07 01:22 UTC
Labels: bug
